//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RebateProcessor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RebateResponse")]
        public string ProducerQueue {
            get {
                return ((string)(this["ProducerQueue"]));
            }
            set {
                this["ProducerQueue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RebateRequest")]
        public string SubscriberQueue {
            get {
                return ((string)(this["SubscriberQueue"]));
            }
            set {
                this["SubscriberQueue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tcp://localhost:61616")]
        public string BrokerUrl {
            get {
                return ((string)(this["BrokerUrl"]));
            }
            set {
                this["BrokerUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.25")]
        public decimal GoldDiscount {
            get {
                return ((decimal)(this["GoldDiscount"]));
            }
            set {
                this["GoldDiscount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2")]
        public decimal SilverDiscount {
            get {
                return ((decimal)(this["SilverDiscount"]));
            }
            set {
                this["SilverDiscount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0")]
        public decimal LoyaltyDiscount {
            get {
                return ((decimal)(this["LoyaltyDiscount"]));
            }
            set {
                this["LoyaltyDiscount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0")]
        public decimal RegularDiscount {
            get {
                return ((decimal)(this["RegularDiscount"]));
            }
            set {
                this["RegularDiscount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500.0")]
        public decimal GoldRebate {
            get {
                return ((decimal)(this["GoldRebate"]));
            }
            set {
                this["GoldRebate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000.0")]
        public decimal GoldDiscountOrderMin {
            get {
                return ((decimal)(this["GoldDiscountOrderMin"]));
            }
            set {
                this["GoldDiscountOrderMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0")]
        public decimal SilverRebate {
            get {
                return ((decimal)(this["SilverRebate"]));
            }
            set {
                this["SilverRebate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000.0")]
        public decimal SilverDiscountOrderMin {
            get {
                return ((decimal)(this["SilverDiscountOrderMin"]));
            }
            set {
                this["SilverDiscountOrderMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500.0")]
        public decimal LoyaltyRebate {
            get {
                return ((decimal)(this["LoyaltyRebate"]));
            }
            set {
                this["LoyaltyRebate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0")]
        public decimal LoyaltyDiscountOrderMin {
            get {
                return ((decimal)(this["LoyaltyDiscountOrderMin"]));
            }
            set {
                this["LoyaltyDiscountOrderMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0")]
        public decimal RegularDiscountOrderMin {
            get {
                return ((decimal)(this["RegularDiscountOrderMin"]));
            }
            set {
                this["RegularDiscountOrderMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0")]
        public decimal RegularRebate {
            get {
                return ((decimal)(this["RegularRebate"]));
            }
            set {
                this["RegularRebate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RebateProcessorDB.mdf")]
        public string DbFileName {
            get {
                return ((string)(this["DbFileName"]));
            }
            set {
                this["DbFileName"] = value;
            }
        }
    }
}
